### ISSUE TITLE
Language issue 

### ISSUE THREAD

**Issue by Bobby-Funk** [bramdebouvere/fltouch#21]
Hello! 

Thanks for the great work by creating this awesome script! 
Having an issue displaying track names when they are named not in English.
For example, I name channel 14 a non-English name and when I switch the faders page from 1st to 2nd (to access channels 9 to 16), the fader page changes, but the names of all channels remain the same (from 1st to 8th). 
Is there a way to add support of any other language but English? 
If this is possible, please describe how to do it.
Big thanx in advance!

**Comment by bramdebouvere** [comment]
Hey Bobby-Funk,

I suppose the device might have some kind of issue with non-ansi characters. The original script also uses utf-8, so I supposed this was correct, but it might not be.

Do you have some text that I could use to simulate this behaviour?

If this is a device-limitation, it might be possible that some characters can not be displayed on the device, and I'll need to filter these out. I'm not sure if, for example, chinese characters can be displayed.

Let me know your example, and I'll see what I can do to fix it.

Kind regards

**Comment by Bobby-Funk** [comment]
Good day Bramdebouvere! 
I do! The language is Russian. Try naming one of the channels on page 2 (from ch.9 to ch.16) in the mixer with the use of any of these:
Example #1: Во
Example #2: Возможно
The examples have a slight difference in behaviour but you will get the point of the problem.
Big thank you in advance!

**Comment by bramdebouvere** [comment]
The device only seems to support ASCII characters (a basic set of 127 characters), so I added some filtering for the track names:

- I added some basic transliteration for ASCII Extended, Cyrillic and Serbian characters. So if you write names now in Russian, you should see an ASCII version of that. I wanted to add more languages by just importing a library, but I cannot easily add dependencies due to the limitations of how FL Studio processes these scripts. So I just ended up writing some basic transliteration logic myself.
- When there is no known transliteration of a character, it just removes the character (not great, but better than the device crashing)

Please have a look if my changes fix the issue for you. You'll need to download the script again, install it, restart your devices and FL Studio.

Let me know how it goes!

**Comment by Bobby-Funk** [comment]
Bramdebouvere, you absolute champion! 
Works like charm, HUGE thank you! 
ps. keep up the great work mate!
