### ISSUE TITLE
template update

### ISSUE THREAD

**Issue by Bobby-Funk** [bramdebouvere/fltouch#22]
@bramdebouvere Hello! 
Sorry, didn't find a way to send you a DM in github or a way to contact you, so crated this issue, but I have no issue :)

Just wana share my version of the template, that Dr. G posted on the FL forum. 
(https://forum.image-line.com/memberlist.php?mode=viewprofile&u=592129)
I upscaled the image and redone the text, so it can be more readable in real use. Print dimensions are the same.
Hope it can be useful to anyone. 
Chears!
 
<img width="1194" alt="modded_upscale3" src="https://github.com/bramdebouvere/fltouch/assets/93488429/58fcecd4-406b-40cb-84f2-9086b6b5f20d">

**Comment by bramdebouvere** [comment]
Hey there, looks great! Thanks for this! The description also seems to be better and more accurate than the one I have on the homepage right now.

The only thing that is different in my script is that name/value is now "rename" instead of the toggle switch it was before.
And holding shift with that button will put all the extenders on the left or on the right. Would it be possible to make a custom version with those changes specifically for my script?

Also, do we need to use any specific print settings to make sure that it prints accurately?

I'll be glad to add this to the readme.

**Comment by Bobby-Funk** [comment]
My pleasure!

<img width="1194" alt="modded_upscale4" src="https://github.com/bramdebouvere/fltouch/assets/93488429/cf50ff29-7763-49e1-a738-79fe292ccb69">

Sadly, I don't have extenders, but thinking about getting one :)

Sorry, can't say anything about the printing settings because I printed it in a printing business, where I will give them only the initial data from Dr. G, that is "The image must be 6.21875 inches wide in A4 size". So don't know what settings they used on there hardware, but fits perfect. At first I asked them to make a black & white draft on regular papper to make sure that it fits and only after I was sure that the size was correct, I asked to print it on an adhesive backing.
And yeah, I made the print as a sticker, works very well :)

Please let me know at any time if any changes are needed.
Chears!

**Comment by bramdebouvere** [comment]
Looks great, thanks! Added it to the readme.
